services:
  - type: web
    name: spring-boot-backend
    env: java
    region: oregon
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    rootDir: backend
